// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNh1Ivm40onFWiCNAIsHMGX6VU3zALyAQ',
    appId: '1:402959993726:web:05b33f25d60e116cac412f',
    messagingSenderId: '402959993726',
    projectId: 'social-app-75bc7',
    authDomain: 'social-app-75bc7.firebaseapp.com',
    storageBucket: 'social-app-75bc7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTl0OBuJRbBVGSZTKmj-CYKGWCY0K8CY',
    appId: '1:402959993726:android:6d87ce03f3649820ac412f',
    messagingSenderId: '402959993726',
    projectId: 'social-app-75bc7',
    storageBucket: 'social-app-75bc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPo53WFQQVFtBUBr59MEbMkURpOILfOdA',
    appId: '1:402959993726:ios:f27b1eb8b38d04e3ac412f',
    messagingSenderId: '402959993726',
    projectId: 'social-app-75bc7',
    storageBucket: 'social-app-75bc7.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
